// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/lazyBoys": {
            "get": {
                "description": "通过请求参数，通知指定人员的今日或者上个工作日工时填写情况。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "工时预警接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "查询类型 0：查询上个工作日工时填写情况；1：查询今日工时填写情况",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "待查询小组成员 由成员拼音组成，成员之间用|隔开",
                        "name": "users",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "code\":400,\"msg\":\"type参数输入有误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "600": {
                        "description": "code\":600,\"msg\":\"请求参数中包含错误的小组成员或成员名有误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "700": {
                        "description": "{\"code\":700,\"msg\":\"今天为非工作日，无需查询以及通报\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "工时预警系统API",
	Description:      "这是一个工时预警系统",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
